name: telegram message
on:
  release:
    types:
      - created
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Configuration message
        id: message-metadata
        run: |
          MESSAGE=$(curl https://raw.githubusercontent.com/smartworldteam/art/main/stubs/messages/release.md)
          VERSION="${GITHUB_REF##*/}"
          REPOSITORY_NAME="${GITHUB_REPOSITORY}"
          $REPOSITORY_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"
          MESSAGE="${MESSAGE/\$REPOSITORY_NAME/$REPOSITORY_NAME}"
          MESSAGE="${MESSAGE/\$REPOSITORY_URL/$REPOSITORY_URL}"
          MESSAGE="${MESSAGE/\$VERSION/$VERSION}"
          echo "::set-output name=body::$MESSAGE"
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ steps.message-metadata.outputs.body }}
